name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: Adityarajx11
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Contribution Snake"
          add: "dist/*.svg"
          pull: "--rebase --autostash"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}